// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ClipboardController from "./clipboard_controller"
application.register("clipboard", ClipboardController)

import FlatpickrController from "./flatpickr_controller"
application.register("flatpickr", FlatpickrController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import LeagueController from "./league_controller"
application.register("league", LeagueController)


import ShareController from "./share_controller"
application.register("share", ShareController)

import TimerController from "./timer_controller"
application.register("timer", TimerController)
